# Generated by Django 5.0.4 on 2026-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked_actions',
            field=models.JSONField(default=list),
        ),
    ]
